# Generated by Django 5.1.5 on 2025-03-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Full name of the customer.', max_length=255)),
                ('invoice_date', models.DateField(auto_now_add=True, help_text='The date when the invoice was created.')),
                ('due_date', models.DateField(help_text='The due date by which payment should be made.')),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', help_text='The current status of the invoice.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255, unique=True)),
                ('sku', models.CharField(help_text='Stock Keeping Unit (SKU) for the product.', max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit of the product.', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(help_text='Name of the vendor.', max_length=255)),
                ('order_date', models.DateField(auto_now_add=True, help_text='The date when the order was placed.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='The current status of the purchase order.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The number of units purchased.')),
                ('price_each', models.DecimalField(decimal_places=2, help_text='The price per unit for the product.', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ecommerce_app.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The number of units ordered.')),
                ('cost', models.DecimalField(decimal_places=2, help_text='The total cost for this line item.', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ecommerce_app.purchaseorder')),
            ],
        ),
    ]
